source 'https://rubygems.org'

gem 'rails', '3.2.7'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'pry'

gem 'activemodel-form', path: '..'
gem 'formtastic'
gem 'simple_form'
