require 'active_model'
require 'active_model/form/attribute_assignment'
require 'active_model/form/version'
require 'active_support/inflector'

module ActiveModel
  class Form
    include ActiveModel::Form::AttributeAssignment
    include ActiveModel::Validations
    include ActiveModel::Conversion
    include ActiveModel
    extend ActiveModel::Naming

    def initialize(attributes=nil)
      self.assign_attributes attributes
    end

    # For the Rails route helpers
    def persisted?
      false
    end

    # Set the model name to change the field names generated by the Rails form helpers
    def self.model_name=(name)
      @_model_name = ActiveModel::Name.new(self, nil, name)
    end

    def self.attribute(name, type_name)
      # TODO: Make inheritance of ActiveModel::Forms do the right thing with attributes
      @_attributes ||= {}
      @_attributes[name.to_sym] = self.type_from_type_name(type_name)
      self.send(:attr_accessor, name)
    end

    def self.attributes
      @_attributes ||= {}
    end

    # Returns the class object for the named attribute.
    def class_for_attribute(name)
      self.class.attributes[name.to_sym]
    end

    # Stolen from ActiveRecord attribute_assignment.rb
    def attributes=(new_attributes, options={})
      return if new_attributes.blank?

      attributes = new_attributes.stringify_keys
      multi_parameter_attributes = []

      attributes.each do |k, v|
        if k.include?("(")
          multi_parameter_attributes << [ k, v ]
        elsif respond_to?("#{k}=")
          if v.is_a?(Hash)
            raise(UnknownAttributeError, "ActiveModel::Form doesn't deal with nested attributes for now: #{k}")
          else
            send("#{k}=", v)
          end
        else
          raise(UnknownAttributeError, "unknown attribute: #{k}")
        end
      end
    end

    protected

    def self.type_from_type_name(type_name)
      classified_type_name = ActiveSupport::Inflector.classify(type_name)
      ActiveSupport::Inflector.safe_constantize(classified_type_name)
    end
  end
end
